### ISSUE TITLE
Implement a specification

### ISSUE THREAD

**Issue by TheReturnOfJan** [leapdao/EthereumMachineOracle#1]
# Bounty

We want to use [refinement](https://en.wikipedia.org/wiki/Refinement_(computing)) as a development strategy in this repository (to the degree it is practical given available tooling). Hence we first need an abstract specification for our executable programs. Solidity [interfaces](https://solidity.readthedocs.io/en/v0.6.3/contracts.html#interfaces) and [abstract contracts](https://solidity.readthedocs.io/en/v0.6.3/contracts.html#abstract-contracts) should be a decent enough specification language. 

## Scope

- Use solidity to specify the programs.

## Deliverables
- interface(s) and partial implementation (in abstract contract(s)) of the Oracle contract compile with no errors
- interface(s) and partial implementation (in abstract contract(s)) of the Court contract compile with no errors

## Gain for the project
Get a solid foundation for EMO

## Roles
bounty gardener: @TheReturnOfJan  / 5%
bounty worker: @TheReturnOfJan  / 80%
bounty reviewer: name / share

## Funded by

Dev Circle

**Comment by troggy** [comment]
what is the spec here? The current state of Court and Oracle contacts?

**Comment by TheReturnOfJan** [comment]
The _current_ state can be considered the spec, more or less.
