### ISSUE TITLE
Deploy Gnosis Safe for EMO (reputation only)

### ISSUE THREAD

**Issue by TheReturnOfJan** [leapdao/EthereumMachineOracle#10]
# Bounty
Deploy a Gnosis Safe instance and transfer 15k to it

## Scope

- Deploy Gnosis safe
- Transfer 15k from General multi-sig to-it
- The reviewer should make sure front-end works (reputation and all)

## Deliverables

- Gnosis safe deployed with 15k in it

## Funding Circle

General

## Bounty Owner/Gardener

@TheReturnOfJan    as ** EMO developer **

## Gain for the Role

EMO finance

## Roles
bounty gardener: @TheReturnOfJan   / 0 DAI 
bounty worker: @roleengineer   / 90%
bounty reviewer: @TheReturnOfJan   / 10%

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by TheReturnOfJan** [comment]
Reputation before:
Roleengineer: `1343433526450609645120`
TheReturnOfJan: `1284760365971368320574`

**Comment by roleengineer** [comment]
Reputation new:
Roleeengineer: `1434882491293165433548`
TheReturnOfJan: `1583668232259326427102`

**Comment by roleengineer** [comment]
New action should be done @johannbarbie @TheReturnOfJan  
As General was migrated from Multisig to Safe the signature for EMO Safe should be also replaced.

**Comment by johannbarbie** [comment]
initialized as *#10*
@TheReturnOfJan plz confirm

**Comment by roleengineer** [comment]
New colony root hash (0xf55b503985399f4fdd8f0bab1ac13a5066c35f6ad6e0807d9927451b9b388d08).
Reputation new:
Roleengineer: `1423873995713603480301`
TheReturnOfJan: `1571518244479764392412`

The values are less than in previous root, but we exactly have delivered few bounties since those time. Is something broken or I'm missing something or I've made some mistake? @johannbarbie

**Comment by roleengineer** [comment]
New root hash (0x423e8e7656eaf52f68c211c91c08c866f32a2b6da48c3f4a3f4ad4111568c8d2).
Reputation:
Roleengineer: `2011722963054542953134`
TheReturnOfJan: `1949204914402152155911`
Everything looks good.
