### ISSUE TITLE
Create deployment script

### ISSUE THREAD

**Issue by TheReturnOfJan** [leapdao/EthereumMachineOracle#5]
# Bounty
Create a script that deploys the EMO stack with the template machine. Make sure we can call the contract.

## Scope

- When the script is run, the code compiles fine and gets deployed successfully 
- One is able to do a simple interaction with the deployed contracts

## Deliverables

- The deployment script
- The interaction script

## Funding Circle

General

## Bounty Owner/Gardener

@TheReturnOfJan  as ** EMO developer **

## Gain for the Role

Progress with roadmap.

## Roles
bounty gardener: @TheReturnOfJan / 50 DAI 
bounty worker: @TheReturnOfJan  / 75%
bounty reviewer: @roleengineer  / share

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by roleengineer** [comment]
Related to this one, two additional bounties should be created. One for implementing new ABI Coder in ether.js, another one for example contract with callback functions.
