### ISSUE TITLE
Identify Solidity compiler bug

### ISSUE THREAD

**Issue by roleengineer** [leapdao/EthereumMachineOracle#6]
# Bounty
Identify the Internal Solidity Compiler Bug that blocks deployment EMO stack.

## Scope

- Find the specific reason that causes the bug
- Create an issue [here](https://github.com/ethereum/solidity/issues/) to fix Compiler Bugs
- Find the solution that doesn't require waiting for updating Compiler

## Deliverables

- Remove the blocker for deployment script
- Help to improve Solidity Compiler

## Funding Circle

General

## Bounty Owner/Gardener

@roleengineer  as ** EMO developer **

## Gain for the Role

Progress with roadmap.

## Roles
bounty gardener: @roleengineer / 0 DAI 
bounty worker: @TheReturnOfJan  / 80%
bounty reviewer: @roleengineer  / 20%

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by TheReturnOfJan** [comment]
Delivery: https://github.com/ethereum/solidity/issues/9037

**Comment by TheReturnOfJan** [comment]
The workaround ended up being:
- Manual calls to library in place of using for 
- Make Merkle a deployed library instead of internal one

The workaround is implemented in #7

**Comment by roleengineer** [comment]
Reviewed:
- Approved finding the сause of the Internal Compiler Bug. The reason was non-implemented in code by Solidity team the standard behavior with structs when copying from calldata to storage happens. (Must work with pragma experimental ABIEncoderV2).
- Approved creating issue.
- Approved workaround with library (making external calls instead internal JUMPs). Contract compiles successfully without any errors, there are several warnings, but it's out of scope.
Cool work and workaround.
