### ISSUE TITLE
Enable ethers to encode function types

### ISSUE THREAD

**Issue by roleengineer** [leapdao/EthereumMachineOracle#8]
# Bounty
Create a new ABI Coder in ethers.js. Make sure that a new instance allows to make function calls with functions as inputs.

## Scope

- Use ethers.js Lowel-Level API to create a new instance of ABI Coder that allows function call with function as input parameter
- Use new instance in test coverage (simple example with call oracle.ask)

## Deliverables

- new ABI Coder instance
- Update test with new possibilities

## Funding Circle

General

## Bounty Owner/Gardener

@roleengineer   as ** EMO developer **

## Gain for the Role

Ability to coverage with tests.

## Roles
bounty gardener: @roleengineer  / 0 DAI 
bounty worker: @TheReturnOfJan  / 75%
bounty reviewer: @roleengineer  / 25%

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by TheReturnOfJan** [comment]
E-Z-P-Z
https://github.com/leapdao/EthereumMachineOracle/blob/f0b9d81e29421dfbcec99bbbce5844baa702a279/deploy.js#L33
