### ISSUE TITLE
Create a minimal example client contract for EMO

### ISSUE THREAD

**Issue by TheReturnOfJan** [leapdao/EthereumMachineOracle#9]
# Bounty
We need an example EMO client to test our contracts. Provide a minimal example. 

## Scope

- Example contract has a method that calls ask on EMO
- Example contract implements a success callback function and passes it in ask
- Example contract implements a fail callback function and passes it in ask

## Deliverables

- a solidity contract that satisfies the scope

## Funding Circle

General

## Bounty Owner/Gardener

@TheReturnOfJan    as ** EMO developer **

## Gain for the Role

Roadmap progress

## Roles
bounty gardener: @TheReturnOfJan   / 0 DAI 
bounty worker: @roleengineer   / 80%
bounty reviewer: @TheReturnOfJan   / 20%

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by TheReturnOfJan** [comment]
> # Bounty
> We need an example EMO client to test our contracts. Provide a minimal example.
> 
> ## Scope
> * Eaxmple contract has a method that calls ask on EMO
> * Example contract implements a success callback function and passes it in ask
> * Example contract implements a fail callback function and passes it in ask
> 
> ## Deliverables
> * a solidity contract that satisfies the scope
> 
> ## Funding Circle
> General
> 
> ## Bounty Owner/Gardener
> @TheReturnOfJan as ** EMO developer **
> 
> ## Gain for the Role
> Roadmap progress
> 
> ## Roles
> bounty gardener: @roleengineer / 0 DAI
> bounty worker: @roleengineer / 80%
> bounty reviewer: @TheReturnOfJan / 20%
> 
> ## Gardener checklist
> * [x]  I have attached one of the `size-` labels to this bounty
> * [x]  I have submitted this bounty via http://bounty.leapdao.org/viewform
> * [x]  I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by johannbarbie** [comment]
paid out together with https://github.com/leapdao/EthereumMachineOracle/issues/8
